// Auto-generated by scripts/pipeline/run.ts. Do not edit by hand.
import type { Episode } from "../types";
import { ericJang } from "./eric-jang";

export const generatedEpisodes: Episode[] = [ericJang];
